spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/back_exam?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT"
    password: test_pwd
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: "root"
server:
  port: 8000
mybatis:
  mapper-locations: "classpath:mapper/*/*.xml"